/*
 * SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or
 * its affiliates is strictly prohibited.
 */

#ifndef SRC_CORE_APPLICATION_INPUTMAPPING_H_
#define SRC_CORE_APPLICATION_INPUTMAPPING_H_

#include <GLFW/glfw3.h>

#include <unordered_map>

#include "Core/Application/Inputs.h"

namespace nv3dvc {
namespace core {
namespace application {
namespace inputs {

const std::unordered_map<int, JoystickHatState> JOYSTICK_HAT_STATE_GLFW_TO_NV3DVC = {
    {GLFW_HAT_CENTERED, JoystickHatState::CENTERED},
    {GLFW_HAT_UP, JoystickHatState::UP},
    {GLFW_HAT_RIGHT, JoystickHatState::RIGHT},
    {GLFW_HAT_DOWN, JoystickHatState::DOWN},
    {GLFW_HAT_LEFT, JoystickHatState::LEFT},
    {GLFW_HAT_RIGHT_UP, JoystickHatState::RIGHT_UP},
    {GLFW_HAT_RIGHT_DOWN, JoystickHatState::RIGHT_DOWN},
    {GLFW_HAT_LEFT_UP, JoystickHatState::LEFT_UP},
    {GLFW_HAT_LEFT_DOWN, JoystickHatState::LEFT_DOWN},
};

const std::unordered_map<int, Key> KEY_GLFW_TO_NV3DVC = {
    {GLFW_KEY_UNKNOWN, Key::UNKNOWN},
    {GLFW_KEY_SPACE, Key::SPACE},
    {GLFW_KEY_APOSTROPHE, Key::APOSTROPHE},
    {GLFW_KEY_COMMA, Key::COMMA},
    {GLFW_KEY_MINUS, Key::MINUS},
    {GLFW_KEY_PERIOD, Key::PERIOD},
    {GLFW_KEY_SLASH, Key::SLASH},
    {GLFW_KEY_0, Key::KEY_0},
    {GLFW_KEY_1, Key::KEY_1},
    {GLFW_KEY_2, Key::KEY_2},
    {GLFW_KEY_3, Key::KEY_3},
    {GLFW_KEY_4, Key::KEY_4},
    {GLFW_KEY_5, Key::KEY_5},
    {GLFW_KEY_6, Key::KEY_6},
    {GLFW_KEY_7, Key::KEY_7},
    {GLFW_KEY_8, Key::KEY_8},
    {GLFW_KEY_9, Key::KEY_9},
    {GLFW_KEY_SEMICOLON, Key::SEMICOLON},
    {GLFW_KEY_EQUAL, Key::EQUAL},
    {GLFW_KEY_A, Key::A},
    {GLFW_KEY_B, Key::B},
    {GLFW_KEY_C, Key::C},
    {GLFW_KEY_D, Key::D},
    {GLFW_KEY_E, Key::E},
    {GLFW_KEY_F, Key::F},
    {GLFW_KEY_G, Key::G},
    {GLFW_KEY_H, Key::H},
    {GLFW_KEY_I, Key::I},
    {GLFW_KEY_J, Key::J},
    {GLFW_KEY_K, Key::K},
    {GLFW_KEY_L, Key::L},
    {GLFW_KEY_M, Key::M},
    {GLFW_KEY_N, Key::N},
    {GLFW_KEY_O, Key::O},
    {GLFW_KEY_P, Key::P},
    {GLFW_KEY_Q, Key::Q},
    {GLFW_KEY_R, Key::R},
    {GLFW_KEY_S, Key::S},
    {GLFW_KEY_T, Key::T},
    {GLFW_KEY_U, Key::U},
    {GLFW_KEY_V, Key::V},
    {GLFW_KEY_W, Key::W},
    {GLFW_KEY_X, Key::X},
    {GLFW_KEY_Y, Key::Y},
    {GLFW_KEY_Z, Key::Z},
    {GLFW_KEY_LEFT_BRACKET, Key::LEFT_BRACKET},
    {GLFW_KEY_BACKSLASH, Key::BACKSLASH},
    {GLFW_KEY_RIGHT_BRACKET, Key::RIGHT_BRACKET},
    {GLFW_KEY_GRAVE_ACCENT, Key::GRAVE_ACCENT},
    {GLFW_KEY_WORLD_1, Key::WORLD_1},
    {GLFW_KEY_WORLD_2, Key::WORLD_2},
    {GLFW_KEY_ESCAPE, Key::ESCAPE},
    {GLFW_KEY_ENTER, Key::ENTER},
    {GLFW_KEY_TAB, Key::TAB},
    {GLFW_KEY_BACKSPACE, Key::BACKSPACE},
    {GLFW_KEY_INSERT, Key::INSRT},
    {GLFW_KEY_DELETE, Key::DEL},
    {GLFW_KEY_RIGHT, Key::RIGHT},
    {GLFW_KEY_LEFT, Key::LEFT},
    {GLFW_KEY_DOWN, Key::DOWN},
    {GLFW_KEY_UP, Key::UP},
    {GLFW_KEY_PAGE_UP, Key::PAGE_UP},
    {GLFW_KEY_PAGE_DOWN, Key::PAGE_DOWN},
    {GLFW_KEY_HOME, Key::HOME},
    {GLFW_KEY_END, Key::END},
    {GLFW_KEY_CAPS_LOCK, Key::CAPS_LOCK},
    {GLFW_KEY_SCROLL_LOCK, Key::SCROLL_LOCK},
    {GLFW_KEY_NUM_LOCK, Key::NUM_LOCK},
    {GLFW_KEY_PRINT_SCREEN, Key::PRINT_SCREEN},
    {GLFW_KEY_PAUSE, Key::PAUSE},
    {GLFW_KEY_F1, Key::F1},
    {GLFW_KEY_F2, Key::F2},
    {GLFW_KEY_F3, Key::F3},
    {GLFW_KEY_F4, Key::F4},
    {GLFW_KEY_F5, Key::F5},
    {GLFW_KEY_F6, Key::F6},
    {GLFW_KEY_F7, Key::F7},
    {GLFW_KEY_F8, Key::F8},
    {GLFW_KEY_F9, Key::F9},
    {GLFW_KEY_F10, Key::F10},
    {GLFW_KEY_F11, Key::F11},
    {GLFW_KEY_F12, Key::F12},
    {GLFW_KEY_F13, Key::F13},
    {GLFW_KEY_F14, Key::F14},
    {GLFW_KEY_F15, Key::F15},
    {GLFW_KEY_F16, Key::F16},
    {GLFW_KEY_F17, Key::F17},
    {GLFW_KEY_F18, Key::F18},
    {GLFW_KEY_F19, Key::F19},
    {GLFW_KEY_F20, Key::F20},
    {GLFW_KEY_F21, Key::F21},
    {GLFW_KEY_F22, Key::F22},
    {GLFW_KEY_F23, Key::F23},
    {GLFW_KEY_F24, Key::F24},
    {GLFW_KEY_F25, Key::F25},
    {GLFW_KEY_KP_0, Key::KP_0},
    {GLFW_KEY_KP_1, Key::KP_1},
    {GLFW_KEY_KP_2, Key::KP_2},
    {GLFW_KEY_KP_3, Key::KP_3},
    {GLFW_KEY_KP_4, Key::KP_4},
    {GLFW_KEY_KP_5, Key::KP_5},
    {GLFW_KEY_KP_6, Key::KP_6},
    {GLFW_KEY_KP_7, Key::KP_7},
    {GLFW_KEY_KP_8, Key::KP_8},
    {GLFW_KEY_KP_9, Key::KP_9},
    {GLFW_KEY_KP_DECIMAL, Key::KP_DECIMAL},
    {GLFW_KEY_KP_DIVIDE, Key::KP_DIVIDE},
    {GLFW_KEY_KP_MULTIPLY, Key::KP_MULTIPLY},
    {GLFW_KEY_KP_SUBTRACT, Key::KP_SUBTRACT},
    {GLFW_KEY_KP_ADD, Key::KP_ADD},
    {GLFW_KEY_KP_ENTER, Key::KP_ENTER},
    {GLFW_KEY_KP_EQUAL, Key::KP_EQUAL},
    {GLFW_KEY_LEFT_SHIFT, Key::LEFT_SHIFT},
    {GLFW_KEY_LEFT_CONTROL, Key::LEFT_CONTROL},
    {GLFW_KEY_LEFT_ALT, Key::LEFT_ALT},
    {GLFW_KEY_LEFT_SUPER, Key::LEFT_SUPER},
    {GLFW_KEY_RIGHT_SHIFT, Key::RIGHT_SHIFT},
    {GLFW_KEY_RIGHT_CONTROL, Key::RIGHT_CONTROL},
    {GLFW_KEY_RIGHT_ALT, Key::RIGHT_ALT},
    {GLFW_KEY_RIGHT_SUPER, Key::RIGHT_SUPER},
    {GLFW_KEY_MENU, Key::MENU},
    {GLFW_KEY_LAST, Key::LAST},
};

const std::unordered_map<int, Modifier> MODIFIER_GLFW_TO_NV3DVC = {
    {0, Modifier::NONE},
    {GLFW_MOD_SHIFT, Modifier::SHIFT},
    {GLFW_MOD_CONTROL, Modifier::CONTROL},
    {GLFW_MOD_ALT, Modifier::ALT},
    {GLFW_MOD_SUPER, Modifier::SUPER},
    {GLFW_MOD_CAPS_LOCK, Modifier::CAPS_LOCK},
    {GLFW_MOD_NUM_LOCK, Modifier::NUM_LOCK},
};

const std::unordered_map<int, Mouse> MOUSE_GLFW_TO_NV3DVC = {
    {GLFW_MOUSE_BUTTON_1, Mouse::BUTTON_1},  {GLFW_MOUSE_BUTTON_2, Mouse::BUTTON_2},
    {GLFW_MOUSE_BUTTON_3, Mouse::BUTTON_3},  {GLFW_MOUSE_BUTTON_4, Mouse::BUTTON_4},
    {GLFW_MOUSE_BUTTON_5, Mouse::BUTTON_5},  {GLFW_MOUSE_BUTTON_6, Mouse::BUTTON_6},
    {GLFW_MOUSE_BUTTON_7, Mouse::BUTTON_7},  {GLFW_MOUSE_BUTTON_8, Mouse::BUTTON_8},
    {GLFW_MOUSE_BUTTON_LAST, Mouse::LAST},   {GLFW_MOUSE_BUTTON_LEFT, Mouse::LEFT},
    {GLFW_MOUSE_BUTTON_RIGHT, Mouse::RIGHT}, {GLFW_MOUSE_BUTTON_MIDDLE, Mouse::MIDDLE},
};

const std::unordered_map<int, Joystick> JOYSTICK_GLFW_TO_NV3DVC = {
    {GLFW_JOYSTICK_1, Joystick::JOYSTICK_1},   {GLFW_JOYSTICK_2, Joystick::JOYSTICK_2},
    {GLFW_JOYSTICK_3, Joystick::JOYSTICK_3},   {GLFW_JOYSTICK_4, Joystick::JOYSTICK_4},
    {GLFW_JOYSTICK_5, Joystick::JOYSTICK_5},   {GLFW_JOYSTICK_6, Joystick::JOYSTICK_6},
    {GLFW_JOYSTICK_7, Joystick::JOYSTICK_7},   {GLFW_JOYSTICK_8, Joystick::JOYSTICK_8},
    {GLFW_JOYSTICK_9, Joystick::JOYSTICK_9},   {GLFW_JOYSTICK_10, Joystick::JOYSTICK_10},
    {GLFW_JOYSTICK_11, Joystick::JOYSTICK_11}, {GLFW_JOYSTICK_12, Joystick::JOYSTICK_12},
    {GLFW_JOYSTICK_13, Joystick::JOYSTICK_13}, {GLFW_JOYSTICK_14, Joystick::JOYSTICK_14},
    {GLFW_JOYSTICK_15, Joystick::JOYSTICK_15}, {GLFW_JOYSTICK_16, Joystick::JOYSTICK_16},
    {GLFW_JOYSTICK_LAST, Joystick::LAST},
};

const std::unordered_map<int, GamepadButton> GAMEPAD_BUTTON_GLFW_TO_NV3DVC = {
    {GLFW_GAMEPAD_BUTTON_A, GamepadButton::A},
    {GLFW_GAMEPAD_BUTTON_B, GamepadButton::B},
    {GLFW_GAMEPAD_BUTTON_X, GamepadButton::X},
    {GLFW_GAMEPAD_BUTTON_Y, GamepadButton::Y},
    {GLFW_GAMEPAD_BUTTON_LEFT_BUMPER, GamepadButton::LEFT_BUMPER},
    {GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER, GamepadButton::RIGHT_BUMPER},
    {GLFW_GAMEPAD_BUTTON_BACK, GamepadButton::BACK},
    {GLFW_GAMEPAD_BUTTON_START, GamepadButton::START},
    {GLFW_GAMEPAD_BUTTON_GUIDE, GamepadButton::GUIDE},
    {GLFW_GAMEPAD_BUTTON_LEFT_THUMB, GamepadButton::LEFT_THUMB},
    {GLFW_GAMEPAD_BUTTON_RIGHT_THUMB, GamepadButton::RIGHT_THUMB},
    {GLFW_GAMEPAD_BUTTON_DPAD_UP, GamepadButton::DPAD_UP},
    {GLFW_GAMEPAD_BUTTON_DPAD_RIGHT, GamepadButton::DPAD_RIGHT},
    {GLFW_GAMEPAD_BUTTON_DPAD_DOWN, GamepadButton::DPAD_DOWN},
    {GLFW_GAMEPAD_BUTTON_DPAD_LEFT, GamepadButton::DPAD_LEFT},
    {GLFW_GAMEPAD_BUTTON_LAST, GamepadButton::LAST},
    {GLFW_GAMEPAD_BUTTON_CROSS, GamepadButton::CROSS},
    {GLFW_GAMEPAD_BUTTON_CIRCLE, GamepadButton::CIRCLE},
    {GLFW_GAMEPAD_BUTTON_SQUARE, GamepadButton::SQUARE},
    {GLFW_GAMEPAD_BUTTON_TRIANGLE, GamepadButton::TRIANGLE},
};

const std::unordered_map<int, GamepadAxis> GAMEPAD_AXIS_GLFW_TO_NV3DVC = {
    {GLFW_GAMEPAD_AXIS_LEFT_X, GamepadAxis::LEFT_X},
    {GLFW_GAMEPAD_AXIS_LEFT_Y, GamepadAxis::LEFT_Y},
    {GLFW_GAMEPAD_AXIS_RIGHT_X, GamepadAxis::RIGHT_X},
    {GLFW_GAMEPAD_AXIS_RIGHT_Y, GamepadAxis::RIGHT_Y},
    {GLFW_GAMEPAD_AXIS_LEFT_TRIGGER, GamepadAxis::LEFT_TRIGGER},
    {GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER, GamepadAxis::RIGHT_TRIGGER},
    {GLFW_GAMEPAD_AXIS_LAST, GamepadAxis::LAST},
};

const std::unordered_map<JoystickHatState, int> JOYSTICK_HAT_STATE_NV3DVC_TO_GLFW = {
    {JoystickHatState::CENTERED, GLFW_HAT_CENTERED},
    {JoystickHatState::UP, GLFW_HAT_UP},
    {JoystickHatState::RIGHT, GLFW_HAT_RIGHT},
    {JoystickHatState::DOWN, GLFW_HAT_DOWN},
    {JoystickHatState::LEFT, GLFW_HAT_LEFT},
    {JoystickHatState::RIGHT_UP, GLFW_HAT_RIGHT_UP},
    {JoystickHatState::RIGHT_DOWN, GLFW_HAT_RIGHT_DOWN},
    {JoystickHatState::LEFT_UP, GLFW_HAT_LEFT_UP},
    {JoystickHatState::LEFT_DOWN, GLFW_HAT_LEFT_DOWN},
};

const std::unordered_map<Key, int> KEY_NV3DVC_TO_GLFW = {
    {Key::UNKNOWN, GLFW_KEY_UNKNOWN},
    {Key::SPACE, GLFW_KEY_SPACE},
    {Key::APOSTROPHE, GLFW_KEY_APOSTROPHE},
    {Key::COMMA, GLFW_KEY_COMMA},
    {Key::MINUS, GLFW_KEY_MINUS},
    {Key::PERIOD, GLFW_KEY_PERIOD},
    {Key::SLASH, GLFW_KEY_SLASH},
    {Key::KEY_0, GLFW_KEY_0},
    {Key::KEY_1, GLFW_KEY_1},
    {Key::KEY_2, GLFW_KEY_2},
    {Key::KEY_3, GLFW_KEY_3},
    {Key::KEY_4, GLFW_KEY_4},
    {Key::KEY_5, GLFW_KEY_5},
    {Key::KEY_6, GLFW_KEY_6},
    {Key::KEY_7, GLFW_KEY_7},
    {Key::KEY_8, GLFW_KEY_8},
    {Key::KEY_9, GLFW_KEY_9},
    {Key::SEMICOLON, GLFW_KEY_SEMICOLON},
    {Key::EQUAL, GLFW_KEY_EQUAL},
    {Key::A, GLFW_KEY_A},
    {Key::B, GLFW_KEY_B},
    {Key::C, GLFW_KEY_C},
    {Key::D, GLFW_KEY_D},
    {Key::E, GLFW_KEY_E},
    {Key::F, GLFW_KEY_F},
    {Key::G, GLFW_KEY_G},
    {Key::H, GLFW_KEY_H},
    {Key::I, GLFW_KEY_I},
    {Key::J, GLFW_KEY_J},
    {Key::K, GLFW_KEY_K},
    {Key::L, GLFW_KEY_L},
    {Key::M, GLFW_KEY_M},
    {Key::N, GLFW_KEY_N},
    {Key::O, GLFW_KEY_O},
    {Key::P, GLFW_KEY_P},
    {Key::Q, GLFW_KEY_Q},
    {Key::R, GLFW_KEY_R},
    {Key::S, GLFW_KEY_S},
    {Key::T, GLFW_KEY_T},
    {Key::U, GLFW_KEY_U},
    {Key::V, GLFW_KEY_V},
    {Key::W, GLFW_KEY_W},
    {Key::X, GLFW_KEY_X},
    {Key::Y, GLFW_KEY_Y},
    {Key::Z, GLFW_KEY_Z},
    {Key::LEFT_BRACKET, GLFW_KEY_LEFT_BRACKET},
    {Key::BACKSLASH, GLFW_KEY_BACKSLASH},
    {Key::RIGHT_BRACKET, GLFW_KEY_RIGHT_BRACKET},
    {Key::GRAVE_ACCENT, GLFW_KEY_GRAVE_ACCENT},
    {Key::WORLD_1, GLFW_KEY_WORLD_1},
    {Key::WORLD_2, GLFW_KEY_WORLD_2},
    {Key::ESCAPE, GLFW_KEY_ESCAPE},
    {Key::ENTER, GLFW_KEY_ENTER},
    {Key::TAB, GLFW_KEY_TAB},
    {Key::BACKSPACE, GLFW_KEY_BACKSPACE},
    {Key::INSRT, GLFW_KEY_INSERT},
    {Key::DEL, GLFW_KEY_DELETE},
    {Key::RIGHT, GLFW_KEY_RIGHT},
    {Key::LEFT, GLFW_KEY_LEFT},
    {Key::DOWN, GLFW_KEY_DOWN},
    {Key::UP, GLFW_KEY_UP},
    {Key::PAGE_UP, GLFW_KEY_PAGE_UP},
    {Key::PAGE_DOWN, GLFW_KEY_PAGE_DOWN},
    {Key::HOME, GLFW_KEY_HOME},
    {Key::END, GLFW_KEY_END},
    {Key::CAPS_LOCK, GLFW_KEY_CAPS_LOCK},
    {Key::SCROLL_LOCK, GLFW_KEY_SCROLL_LOCK},
    {Key::NUM_LOCK, GLFW_KEY_NUM_LOCK},
    {Key::PRINT_SCREEN, GLFW_KEY_PRINT_SCREEN},
    {Key::PAUSE, GLFW_KEY_PAUSE},
    {Key::F1, GLFW_KEY_F1},
    {Key::F2, GLFW_KEY_F2},
    {Key::F3, GLFW_KEY_F3},
    {Key::F4, GLFW_KEY_F4},
    {Key::F5, GLFW_KEY_F5},
    {Key::F6, GLFW_KEY_F6},
    {Key::F7, GLFW_KEY_F7},
    {Key::F8, GLFW_KEY_F8},
    {Key::F9, GLFW_KEY_F9},
    {Key::F10, GLFW_KEY_F10},
    {Key::F11, GLFW_KEY_F11},
    {Key::F12, GLFW_KEY_F12},
    {Key::F13, GLFW_KEY_F13},
    {Key::F14, GLFW_KEY_F14},
    {Key::F15, GLFW_KEY_F15},
    {Key::F16, GLFW_KEY_F16},
    {Key::F17, GLFW_KEY_F17},
    {Key::F18, GLFW_KEY_F18},
    {Key::F19, GLFW_KEY_F19},
    {Key::F20, GLFW_KEY_F20},
    {Key::F21, GLFW_KEY_F21},
    {Key::F22, GLFW_KEY_F22},
    {Key::F23, GLFW_KEY_F23},
    {Key::F24, GLFW_KEY_F24},
    {Key::F25, GLFW_KEY_F25},
    {Key::KP_0, GLFW_KEY_KP_0},
    {Key::KP_1, GLFW_KEY_KP_1},
    {Key::KP_2, GLFW_KEY_KP_2},
    {Key::KP_3, GLFW_KEY_KP_3},
    {Key::KP_4, GLFW_KEY_KP_4},
    {Key::KP_5, GLFW_KEY_KP_5},
    {Key::KP_6, GLFW_KEY_KP_6},
    {Key::KP_7, GLFW_KEY_KP_7},
    {Key::KP_8, GLFW_KEY_KP_8},
    {Key::KP_9, GLFW_KEY_KP_9},
    {Key::KP_DECIMAL, GLFW_KEY_KP_DECIMAL},
    {Key::KP_DIVIDE, GLFW_KEY_KP_DIVIDE},
    {Key::KP_MULTIPLY, GLFW_KEY_KP_MULTIPLY},
    {Key::KP_SUBTRACT, GLFW_KEY_KP_SUBTRACT},
    {Key::KP_ADD, GLFW_KEY_KP_ADD},
    {Key::KP_ENTER, GLFW_KEY_KP_ENTER},
    {Key::KP_EQUAL, GLFW_KEY_KP_EQUAL},
    {Key::LEFT_SHIFT, GLFW_KEY_LEFT_SHIFT},
    {Key::LEFT_CONTROL, GLFW_KEY_LEFT_CONTROL},
    {Key::LEFT_ALT, GLFW_KEY_LEFT_ALT},
    {Key::LEFT_SUPER, GLFW_KEY_LEFT_SUPER},
    {Key::RIGHT_SHIFT, GLFW_KEY_RIGHT_SHIFT},
    {Key::RIGHT_CONTROL, GLFW_KEY_RIGHT_CONTROL},
    {Key::RIGHT_ALT, GLFW_KEY_RIGHT_ALT},
    {Key::RIGHT_SUPER, GLFW_KEY_RIGHT_SUPER},
    {Key::MENU, GLFW_KEY_MENU},
    {Key::LAST, GLFW_KEY_LAST},
};

const std::unordered_map<Modifier, int> MODIFIER_NV3DVC_TO_GLFW = {
    {Modifier::NONE, 0},
    {Modifier::SHIFT, GLFW_MOD_SHIFT},
    {Modifier::CONTROL, GLFW_MOD_CONTROL},
    {Modifier::ALT, GLFW_MOD_ALT},
    {Modifier::SUPER, GLFW_MOD_SUPER},
    {Modifier::CAPS_LOCK, GLFW_MOD_CAPS_LOCK},
    {Modifier::NUM_LOCK, GLFW_MOD_NUM_LOCK},
};

const std::unordered_map<Mouse, int> MOUSE_NV3DVC_TO_GLFW = {
    {Mouse::BUTTON_1, GLFW_MOUSE_BUTTON_1},  {Mouse::BUTTON_2, GLFW_MOUSE_BUTTON_2},
    {Mouse::BUTTON_3, GLFW_MOUSE_BUTTON_3},  {Mouse::BUTTON_4, GLFW_MOUSE_BUTTON_4},
    {Mouse::BUTTON_5, GLFW_MOUSE_BUTTON_5},  {Mouse::BUTTON_6, GLFW_MOUSE_BUTTON_6},
    {Mouse::BUTTON_7, GLFW_MOUSE_BUTTON_7},  {Mouse::BUTTON_8, GLFW_MOUSE_BUTTON_8},
    {Mouse::LAST, GLFW_MOUSE_BUTTON_LAST},   {Mouse::LEFT, GLFW_MOUSE_BUTTON_LEFT},
    {Mouse::RIGHT, GLFW_MOUSE_BUTTON_RIGHT}, {Mouse::MIDDLE, GLFW_MOUSE_BUTTON_MIDDLE},
};

const std::unordered_map<Joystick, int> JOYSTICK_NV3DVC_TO_GLFW = {
    {Joystick::JOYSTICK_1, GLFW_JOYSTICK_1},   {Joystick::JOYSTICK_2, GLFW_JOYSTICK_2},
    {Joystick::JOYSTICK_3, GLFW_JOYSTICK_3},   {Joystick::JOYSTICK_4, GLFW_JOYSTICK_4},
    {Joystick::JOYSTICK_5, GLFW_JOYSTICK_5},   {Joystick::JOYSTICK_6, GLFW_JOYSTICK_6},
    {Joystick::JOYSTICK_7, GLFW_JOYSTICK_7},   {Joystick::JOYSTICK_8, GLFW_JOYSTICK_8},
    {Joystick::JOYSTICK_9, GLFW_JOYSTICK_9},   {Joystick::JOYSTICK_10, GLFW_JOYSTICK_10},
    {Joystick::JOYSTICK_11, GLFW_JOYSTICK_11}, {Joystick::JOYSTICK_12, GLFW_JOYSTICK_12},
    {Joystick::JOYSTICK_13, GLFW_JOYSTICK_13}, {Joystick::JOYSTICK_14, GLFW_JOYSTICK_14},
    {Joystick::JOYSTICK_15, GLFW_JOYSTICK_15}, {Joystick::JOYSTICK_16, GLFW_JOYSTICK_16},
    {Joystick::LAST, GLFW_JOYSTICK_LAST},
};

const std::unordered_map<GamepadButton, int> GAMEPAD_BUTTON_NV3DVC_TO_GLFW = {
    {GamepadButton::A, GLFW_GAMEPAD_BUTTON_A},
    {GamepadButton::B, GLFW_GAMEPAD_BUTTON_B},
    {GamepadButton::X, GLFW_GAMEPAD_BUTTON_X},
    {GamepadButton::Y, GLFW_GAMEPAD_BUTTON_Y},
    {GamepadButton::LEFT_BUMPER, GLFW_GAMEPAD_BUTTON_LEFT_BUMPER},
    {GamepadButton::RIGHT_BUMPER, GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER},
    {GamepadButton::BACK, GLFW_GAMEPAD_BUTTON_BACK},
    {GamepadButton::START, GLFW_GAMEPAD_BUTTON_START},
    {GamepadButton::GUIDE, GLFW_GAMEPAD_BUTTON_GUIDE},
    {GamepadButton::LEFT_THUMB, GLFW_GAMEPAD_BUTTON_LEFT_THUMB},
    {GamepadButton::RIGHT_THUMB, GLFW_GAMEPAD_BUTTON_RIGHT_THUMB},
    {GamepadButton::DPAD_UP, GLFW_GAMEPAD_BUTTON_DPAD_UP},
    {GamepadButton::DPAD_RIGHT, GLFW_GAMEPAD_BUTTON_DPAD_RIGHT},
    {GamepadButton::DPAD_DOWN, GLFW_GAMEPAD_BUTTON_DPAD_DOWN},
    {GamepadButton::DPAD_LEFT, GLFW_GAMEPAD_BUTTON_DPAD_LEFT},
    {GamepadButton::LAST, GLFW_GAMEPAD_BUTTON_LAST},
    {GamepadButton::CROSS, GLFW_GAMEPAD_BUTTON_CROSS},
    {GamepadButton::CIRCLE, GLFW_GAMEPAD_BUTTON_CIRCLE},
    {GamepadButton::SQUARE, GLFW_GAMEPAD_BUTTON_SQUARE},
    {GamepadButton::TRIANGLE, GLFW_GAMEPAD_BUTTON_TRIANGLE},
};

const std::unordered_map<GamepadAxis, int> GAMEPAD_AXIS_NV3DVC_TO_GLFW = {
    {GamepadAxis::LEFT_X, GLFW_GAMEPAD_AXIS_LEFT_X},
    {GamepadAxis::LEFT_Y, GLFW_GAMEPAD_AXIS_LEFT_Y},
    {GamepadAxis::RIGHT_X, GLFW_GAMEPAD_AXIS_RIGHT_X},
    {GamepadAxis::RIGHT_Y, GLFW_GAMEPAD_AXIS_RIGHT_Y},
    {GamepadAxis::LEFT_TRIGGER, GLFW_GAMEPAD_AXIS_LEFT_TRIGGER},
    {GamepadAxis::RIGHT_TRIGGER, GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER},
    {GamepadAxis::LAST, GLFW_GAMEPAD_AXIS_LAST},
};

}  // namespace inputs
}  // namespace application
}  // namespace core
}  // namespace nv3dvc

#endif  // SRC_CORE_APPLICATION_INPUTMAPPING_H_
