#define NVIDIA_AUDIOFX_SDK_VERSION_MAJOR 2
#define NVIDIA_AUDIOFX_SDK_VERSION_MINOR 0
#define NVIDIA_AUDIOFX_SDK_VERSION_RELEASE 0
#define NVIDIA_AUDIOFX_SDK_VERSION_BUILD 20
#define NVIDIA_AUDIOFX_SDK_VERSION 2, 0, 0, 20
#define NVIDIA_AUDIOFX_SDK_VERSION_MAJOR_MINOR 2, 0
#define NVIDIA_AUDIOFX_SDK_VERSION_STRING "2.0.0.20"
#define NVIDIA_AUDIOFX_SDK_VERSION_STRING_MAJOR_MINOR "2.0"
#define NVIDIA_AUDIOFX_SDK_VERSION_STRING_SHORT "2.0.0"
